# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DuanshuSDK Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'WebViewJavascriptBridge', '4.1'
  #pod 'WebViewJavascriptBridge', '6.0'
  pod 'TZImagePickerController'
  pod 'MWPhotoBrowser'
   
  # source 
#  pod 'DuanshuSDK', path: '../../../../.'

  # framewok
#   pod 'DuanshuSDK', path: '../../.'

  pod 'DuanshuSDK', '~> 1.0.4'
end
